### ISSUE TITLE
Error: Unhandled stream error in pipe

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/generator-watson#2]
Error when entering "gulp deploy"

>stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write after end
    at writeAfterEnd (/Users/britanyponvelle/Documents/Watson/11_Watson Products/LT/language-translation/node_modules/gulp-minify-css/node_modules/readable-stream/lib/_stream_writable.js:188:12)
    at Transform.Writable.write (/Users/britanyponvelle/Documents/Watson/11_Watson Products/LT/language-translation/node_modules/gulp-minify-css/node_modules/readable-stream/lib/_stream_writable.js:233:5)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at Stream.endStream (/Users/britanyponvelle/Documents/Watson/11_Watson Products/LT/language-translation/node_modules/gulp-usemin/node_modules/gulp-concat/index.js:90:10)
    at _end (/Users/britanyponvelle/Documents/Watson/11_Watson Products/LT/language-translation/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/britanyponvelle/Documents/Watson/11_Watson Products/LT/language-translation/node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:74:5)
    at Transform.onend (/Users/britanyponvelle/Documents/Watson/11_Watson Products/LT/language-translation/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:199:16)
    at Transform.emit (events.js:129:20)

[GitLab Repo](https://git.design.ibm.com/blponvel/language-translation/tree/master)

**Comment by Snugug** [comment]
Seems to be related to https://github.com/zont/gulp-usemin/issues/125. Investigating…

**Comment by Snugug** [comment]
I've found a replacement. Building it out now

**Comment by Snugug** [comment]
Resolved here:
https://github.com/Snugug/gulp-armadillo/commit/780ebde889e0ec033d07f44a8f32c3b7216ba8ec

Now updating the Yeoman generator
